name: Build and Deploy OpenDocs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Debug - List repository contents
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Looking for package.json files:"
          find . -name "package.json" -type f
          
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          elif [ -f "docs/package.json" ]; then
            cd docs && npm install
          elif [ -f "website/package.json" ]; then
            cd website && npm install
          else
            echo "No package.json found in expected locations"
            exit 1
          fi
          
      - name: Build OpenDocs
        run: |
          if [ -f "package.json" ]; then
            npm run build
          elif [ -f "docs/package.json" ]; then
            cd docs && npm run build
          elif [ -f "website/package.json" ]; then
            cd website && npm run build
          else
            echo "No build script found"
            exit 1
          fi
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
